import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import { Slide, ToastContainer } from 'react-toastify';

import Footer from '@/lib/layout/Footer';
import Header from '@/lib/layout/Header';

import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="grid grid-rows-layout grid-cols-[100%] [grid-template-areas:'header''main''footer'] min-h-screen">
          <Header />
          <main className="py-8">{children}</main>
          <Footer />
        </div>
        <ToastContainer hideProgressBar={true} transition={Slide} position="top-right" limit={5} />
      </body>
    </html>
  );
};

export default RootLayout;
